name: Python Tests

on:
  push:
    branches:
      - main  # Change this if you're using a different branch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python_task/requirements.txt  # If you have any dependencies
        
    - name: Run tests
      run: |
        python -m unittest python_task.test_filter_list
